# Generated by Django 5.0.1 on 2024-02-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='mail',
        ),
    ]
