# Generated by Django 5.0.1 on 2024-02-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_name_contactus_mail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
