# Generated by Django 5.0.1 on 2024-02-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_contactus_contact_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
    ]
