# Generated by Django 5.0.1 on 2024-02-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contact_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
