# Generated by Django 5.0.1 on 2024-02-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('pinterest', models.URLField()),
                ('logo', models.ImageField(upload_to='media/logo/')),
                ('blog_bg_image', models.ImageField(upload_to='media/blog/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
