# Generated by Django 5.0.1 on 2024-02-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='blog_title',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
