# Generated by Django 5.0.1 on 2024-02-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_setting_blog_title_alter_setting_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='blog_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog/'),
        ),
    ]
