# Generated by Django 5.0.1 on 2024-02-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_setting_blog_bg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='blog_bg_image',
        ),
    ]
