# Generated by Django 5.0.1 on 2024-02-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_setting_blog_bg_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='title',
            new_name='name',
        ),
    ]
