# Generated by Django 5.0.1 on 2024-02-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_title_setting_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='blog_title',
            new_name='title',
        ),
    ]
