# Generated by Django 5.0.1 on 2024-02-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_title_setting_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='blog_title',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
