# Generated by Django 5.0.1 on 2024-03-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
