# Generated by Django 5.0.1 on 2024-04-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_blog_slug_alter_blog_slug_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=' ', upload_to='media/shop/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default=' ', upload_to='media/shop/'),
            preserve_default=False,
        ),
    ]
