# Generated by Django 5.0.1 on 2024-04-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_product_image2_product_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_min',
            field=models.ImageField(default=' ', upload_to='media/shop/'),
            preserve_default=False,
        ),
    ]
