# Generated by Django 4.2.10 on 2024-05-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='salam', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
