# Generated by Django 4.2.10 on 2024-05-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='background_photo1',
            field=models.ImageField(default=' ', upload_to='media/background'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='background_photo2',
            field=models.ImageField(default=' ', upload_to='media/background'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='background_photo3',
            field=models.ImageField(default='assd', upload_to='media/background'),
            preserve_default=False,
        ),
    ]
