# Generated by Django 4.2.10 on 2024-10-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_blog_slug_az_remove_blog_slug_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
