# Generated by Django 4.2.10 on 2025-03-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_oneclickorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
