# Generated by Django 4.2.10 on 2025-03-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_productattribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
