version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # Nginx default config faylını comment etdik:
      # - ../nginx.conf:/etc/nginx/nginx.conf
      - ../../static:/app/static
      - ../../media:/app/media
    networks:
      - nginx-net

  app:
    container_name: app
    build: ../..
    restart: always
    env_file: .env
    environment:
      - VIRTUAL_HOST=167.71.55.217
      - VIRTUAL_PORT=8000
      - HTTP_PORT=8000
    volumes:
      - ../..:/code
    expose:
      - "8000"
    networks:
      - nginx-net
    depends_on:
      - postgres

  postgres:
    container_name: postgres-db
    image: postgres:13
    ports:
      - "5433:5432"
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .env
    networks:
      - nginx-net

  redis:
    build:
      context: .
      dockerfile: redis.dockerfile
    image: redis:4.0.11
    restart: on-failure
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redisdb:/var/lib/redis
    env_file: .env
    networks:
      - nginx-net

  celery:
    restart: always
    build: ../..
    container_name: celery
    env_file: .env
    command: celery --app=rest_framework.celery:app worker -B --loglevel=INFO
    volumes:
      - ../..:/code
    depends_on:
      - redis
      - postgres
    networks:
      - nginx-net

networks:
  nginx-net:
    external: true
